[jenkins_server]
jenkins-server ansible_host=YOUR_JENKINS_SERVER_IP ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/medcare-key.pem

[k8s_nodes]
# Add your EKS worker nodes here if doing manual configuration
# worker1 ansible_host=10.0.1.10 ansible_user=ec2-user

[all:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
